Feature/farming
cryptoalgebra/integral-ui pull request #1
Opened 2024-03-06 07:34 UTC by damnnou

2024-03-11 06:20 UTC, lilchizh requested changes

2024-03-11 06:20 UTC, lilchizh commented on src/hooks/farming/useFarmIntegralActions.ts
>  const useFarmIntegralActions = ({
Давай перепишем вызовы на такой формат, как в остальном приложении. Для примера:
https://github.com/cryptoalgebra/integral-ui/blob/master/src/hooks/common/useApprove.ts

То есть, каждый вызов состоит из `usePrepareContractWrite`, `useContractWrite` и `useTransitionAwait`

2024-03-11 06:20 UTC, lilchizh commented on src/hooks/farming/useFarmIntegralActions.ts
> +    rewardToken: `0x${string}`;
Везде вместо `0x{string}` - `Address` из viem

2024-03-11 06:22 UTC, lilchizh requested changes

2024-03-11 06:22 UTC, lilchizh commented on src/components/farming/ActiveFarming/index.tsx
> +    const [isLoading, setIsLoading] = useState<boolean>(false);
Соответственно, отдельные стейты для загрузок будут не нужны

2024-03-11 06:37 UTC, lilchizh requested changes

2024-03-11 06:37 UTC, lilchizh commented on src/components/farming/ActiveFarming/index.tsx
> +        tokenId: BigInt(deposits[2].id),
Хардкод

2024-03-11 06:37 UTC, lilchizh commented on src/components/farming/ActiveFarming/index.tsx
> +    }, []);
`deposits` , `farming` в зависимости

2024-03-14 07:11 UTC, lilchizh approved these changes

2024-03-14 07:11 UTC, lilchizh commented on src/hooks/farming/useActiveFarming.ts
> +        isLoading: isLoading || deposits === undefined,
areDepositsLoading из useDepositsQuery

2024-03-14 07:11 UTC, lilchizh commented on src/hooks/farming/useClosedFarmings.ts
> +    useEffect(() => {
Через useMemo думаю будет лучше

2024-03-14 07:11 UTC, lilchizh commented on src/hooks/farming/useFarmHarvest.ts
> +        address: account && tokenId ? FARMING_CENTER : undefined,
А для usePrepareContractWrite есть смысл в адресе чекать на что-то? Я всегда просто оставлял его, не чекал. Если undefined, то запрос не шлется?

2024-03-14 07:11 UTC, lilchizh commented on src/hooks/positions/usePositions.ts
> +    if (!positionInFarming) return null;
Просто return, иначе возвращаемый тип Deposit | undefined | null

2024-03-14 07:11 UTC, lilchizh commented on src/hooks/positions/usePositions.ts
> +    else return positionInFarming;
И без else

2024-03-14 07:11 UTC, lilchizh commented on src/pages/Pool/index.tsx
> +                inFarming: currentPosition?.eternalFarming ? true : false,
Boolean(currentPosition?.eternalFarming)

2024-03-14 08:28 UTC, damnnou commented on src/components/position/PositionCard/index.tsx
> +    const farmingArgs = {
активный фарминг забирается в компоненте src/components/position/CollectFarmings/index.tsx, там свои аргументы

2024-03-14 11:40 UTC, merged