Feature/AddLiquidityButton
cryptoalgebra/integral-ui pull request #5
Opened 2024-03-15 07:59 UTC by damnnou

2024-03-15 08:01 UTC, damnnou commented on src/components/position/IncreaseLiquidityButton/index.tsx
> +                    ),
Насколько норм история amountMin ставить равным amountDesired?

2024-03-15 08:25 UTC, lilchizh requested changes

2024-03-15 08:25 UTC, lilchizh commented on src/components/position/PositionCard/index.tsx
> +            {selectedPosition.liquidityUSD > 0 && (
Лучше проверять просто на ликвидность, а не на ее значение в долларах, потому что его может не быть

2024-03-15 08:25 UTC, lilchizh commented on src/components/position/PositionCard/index.tsx
> +            {selectedPosition.liquidityUSD === 0 && positionEntity && (
Тоже самое

2024-03-15 08:25 UTC, lilchizh commented on src/components/position/IncreaseLiquidityButton/index.tsx
> +        approvalStateA === ApprovalState.NOT_APPROVED ||
Вынести в showApproveA и showApproveB и переиспользовать

2024-03-15 08:25 UTC, lilchizh commented on src/components/position/IncreaseLiquidityButton/index.tsx
> +                    ),
Можно через СДК получить правильную колдату и value. То же самое, только без полей `recipient` и `createPool`  + добавить поле `tokenId`.

https://github.com/cryptoalgebra/integral-ui/blob/4503ab295be37d85d2a1fa7c3983aaebed1b0c07/src/components/create-position/AddLiquidityButton/index.tsx#L46

2024-03-20 13:41 UTC, lilchizh approved these changes

2024-03-20 13:41 UTC, lilchizh commented on src/components/create-position/AddLiquidityButton/index.tsx
> +            mintInfo.position.amount0.numerator.toString() === '0'
Зачем? amount0 может не быть, если позиция только в одном токене.

2024-03-20 13:41 UTC, lilchizh commented on src/components/create-position/AddLiquidityButton/index.tsx
> +    const showApproveA =
Давай выше вынесем :) Перед isReady

2024-03-20 13:41 UTC, lilchizh commented on src/components/create-position/AddLiquidityButton/index.tsx
> +    }, [mintInfo, account]);
useNative, txDeadline в список зависимостей

2024-03-20 13:41 UTC, lilchizh commented on src/components/position/IncreaseLiquidityButton/index.tsx
> +    }, [mintInfo, account]);
tokenId, useNative, txDeadline в список зависимостей

2024-03-20 13:41 UTC, lilchizh commented on src/components/position/IncreaseLiquidityButton/index.tsx
> +    const showApproveA =
Тоже давай перед isReady

2024-03-20 14:31 UTC, damnnou commented on src/components/create-position/AddLiquidityButton/index.tsx
> +            mintInfo.position.amount0.numerator.toString() === '0'
Приложение падало с ошибкой "Invariant failed" при вводе 0.000000000000000001 в инпут токен0.
0.000000000000000001 - это когда mintInfo.position.amount0.numerator = [0, sign: false] (либо просто [sign: false]), .toString() сводит JSBI к строке, и если число меньше, чем может быть посчитано, то коллдата не считается

2024-03-22 07:15 UTC, merged